/**
 * @enum Import declaration type
 */
export enum ImportType {
  NAMESPACE_IMPORT = "NAMESPACE_IMPORT",
  NAMED_IMPORT = "NAMED_IMPORT",
  DEFAULT_IMPORT = "DEFAULT_IMPORT",
  DEFAULT_WITH_NAMED_IMPORT = "DEFAULT_WITH_NAMED_IMPORT",
  DIRECTLY_IMPORT = "DIRECTLY_IMPORT",
}
