name: TSMorpher CI

on:
  push:
    branches: [master, main]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    name: Build

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          yarn

      - name: Bootstrap
        run: |
          lerna bootstrap --no-ci --force-local
          lerna link

      - name: Build Project
        run: yarn build

      - name: Unit Tests
        if: runner.os != 'Windows'
        run: |
          yarn test
          bash <(curl -s https://codecov.io/bash)
